Repository amendx/vue-dndrop, pull requests merged in 2022-10, with the labels that each got.

#63 fix(core): prevent container mismatch in dual instances #60
  docs/src/.vuepress/components/events.vue
  src/utils/container/mediator.js
Labels: enhancement, hacktoberfest

#65 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#67 fix(typo): mismatch import declaration
  src/Container.js
  src/main.js
  src/utils/container/container.js
Labels: hacktoberfest-accepted, hacktoberfest

#68 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#69 Update using-vue.md
  docs/src/guide/using-vue.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#70 Update installation.md
  docs/src/guide/installation.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest
